services:
  - type: web
    name: telegraf
    env: go
    plan: free
    buildCommand: go build -o server
    startCommand: ./server
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: "8081"  # HTTP порт для health checks
      - key: TCP_PORT  
        value: "10000" # TCP порт для вашего приложения