services:
  - type: web
    name: telegraf
    env: go
    plan: free
    buildCommand: go build -o server
    startCommand: ./server
    envVars:
      - key: ENVIRONMENT
        value: production