services:
  - type: web
    name: telegraf
    env: go
    plan: free
    buildCommand: mkdir -p bin && go build -o bin/telegraf
    startCommand: ./bin/telegraf
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        value: 8080
      - key: HTTP_PORT
        value: 8081